FROM postgres14
COPY /home/cristian/Documents/College/2024-II/DB/Project/schema.sql/docker-entrypoint-initdb.d/00-schema.sql
COPY /home/cristian/Documents/College/2024-II/DB/Project/data.sql /docker-entrypoint-initdb.d/01-data.sql


